version: "3.8"

services:
  next_app:
    image: next_wow_marketplace
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
    environment:
      NODE_ENV: production

networks:
  default:
    name: ext_lan
    external: true
